"""
LangGraph state definition (Phase 11 redesign).

State for the new pipeline:
    build_profile → generate_titles → evaluate_titles
        → (refine ONCE) → save_roadmap
        → generate_prompts → evaluate_prompts
        → (refine ONCE) → save_prompts → END

Lessons are no longer generated by the graph. They are generated
lazily, on demand, from the API.
"""

from __future__ import annotations

from typing import TypedDict

from app.schemas.profile import UserProfile
from app.schemas.roadmap import RoadmapTitles, RoadmapTitlesCritique
from app.schemas.teaching import (
    TeachingPromptSet,
    TeachingPromptSetCritique,
)


class LearningState(TypedDict, total=False):
    """
    State for the learning graph.

    `total=False` lets nodes return partial updates.
    """

    # --- Input -------------------------------------------------------
    session_id: int
    raw_input: str
    profile_answers: dict[str, str]

    # --- Profile -----------------------------------------------------
    profile: UserProfile

    # --- Roadmap titles ----------------------------------------------
    roadmap: RoadmapTitles
    roadmap_critique: RoadmapTitlesCritique
    roadmap_iterations: int
    roadmap_acceptable: bool

    # --- Teaching prompts -------------------------------------------
    prompt_set: TeachingPromptSet
    prompt_set_critique: TeachingPromptSetCritique
    prompt_set_iterations: int
    prompt_set_acceptable: bool

    # --- Status ------------------------------------------------------
    status: str
    errors: list[str]


__all__ = ["LearningState"]
