"""initial schema with composite unique

Revision ID: 7b48397c11f6
Revises: 
Create Date: 2026-09-11 21:55:04.030943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b48397c11f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_external_id'), ['external_id'], unique=True)

    op.create_table('study_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('learning_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('goal', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=False),
    sa.Column('learning_style', sa.String(length=50), nullable=False),
    sa.Column('focus', sa.Text(), nullable=True),
    sa.Column('raw_input', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['study_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_profiles_session_id'), ['session_id'], unique=True)

    op.create_table('progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('current_module_index', sa.Integer(), nullable=False),
    sa.Column('current_part_index', sa.Integer(), nullable=False),
    sa.Column('completed_parts', sa.JSON(), nullable=False),
    sa.Column('total_parts', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['study_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_progress_session_id'), ['session_id'], unique=True)

    op.create_table('roadmaps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('total_modules', sa.Integer(), nullable=False),
    sa.Column('estimated_hours', sa.Float(), nullable=False),
    sa.Column('prerequisites', sa.JSON(), nullable=False),
    sa.Column('learning_outcomes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['study_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roadmaps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roadmaps_session_id'), ['session_id'], unique=True)

    op.create_table('roadmap_modules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('roadmap_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roadmap_id', 'module_id', name='uq_roadmap_module')
    )
    with op.batch_alter_table('roadmap_modules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roadmap_modules_roadmap_id'), ['roadmap_id'], unique=False)

    op.create_table('roadmap_parts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('requires_code', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('teaching_plan', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['roadmap_modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_id', 'part_id', name='uq_module_part')
    )
    with op.batch_alter_table('roadmap_parts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roadmap_parts_module_id'), ['module_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roadmap_parts_part_id'), ['part_id'], unique=False)

    op.create_table('lessons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('roadmap_part_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('lesson_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_part_id'], ['roadmap_parts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lessons_roadmap_part_id'), ['roadmap_part_id'], unique=True)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('roadmap_part_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_part_id'], ['roadmap_parts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['study_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_roadmap_part_id'), ['roadmap_part_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_session_id'))
        batch_op.drop_index(batch_op.f('ix_messages_roadmap_part_id'))

    op.drop_table('messages')
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lessons_roadmap_part_id'))

    op.drop_table('lessons')
    with op.batch_alter_table('roadmap_parts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roadmap_parts_part_id'))
        batch_op.drop_index(batch_op.f('ix_roadmap_parts_module_id'))

    op.drop_table('roadmap_parts')
    with op.batch_alter_table('roadmap_modules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roadmap_modules_roadmap_id'))

    op.drop_table('roadmap_modules')
    with op.batch_alter_table('roadmaps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roadmaps_session_id'))

    op.drop_table('roadmaps')
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_progress_session_id'))

    op.drop_table('progress')
    with op.batch_alter_table('learning_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_profiles_session_id'))

    op.drop_table('learning_profiles')
    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_study_sessions_status'))

    op.drop_table('study_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_external_id'))

    op.drop_table('users')
    # ### end Alembic commands ###
