"""phase11 redesign roadmap and lesson models

Revision ID: b8f816a7712e
Revises: 7b48397c11f6
Create Date: 2026-09-15 17:34:28.977829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'b8f816a7712e'
down_revision: Union[str, Sequence[str], None] = '7b48397c11f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_profiles', schema=None) as batch_op:
        batch_op.drop_column('focus')

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('lesson_metadata',
               existing_type=sqlite.JSON(),
               nullable=True)

    with op.batch_alter_table('roadmap_modules', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('roadmap_parts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teaching_prompt', sa.Text(), nullable=True))
        batch_op.drop_column('difficulty')
        batch_op.drop_column('teaching_plan')
        batch_op.drop_column('objective')
        batch_op.drop_column('requires_code')

    with op.batch_alter_table('roadmaps', schema=None) as batch_op:
        batch_op.drop_column('prerequisites')
        batch_op.drop_column('learning_outcomes')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roadmaps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('learning_outcomes', sqlite.JSON(), nullable=False))
        batch_op.add_column(sa.Column('prerequisites', sqlite.JSON(), nullable=False))

    with op.batch_alter_table('roadmap_parts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requires_code', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('objective', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('teaching_plan', sqlite.JSON(), nullable=False))
        batch_op.add_column(sa.Column('difficulty', sa.INTEGER(), nullable=False))
        batch_op.drop_column('teaching_prompt')

    with op.batch_alter_table('roadmap_modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=False))

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.alter_column('lesson_metadata',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('learning_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('focus', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
