"""phase11 redesign roadmap and lesson models

Revision ID: caa6e1b8a5f6
Revises: b8f816a7712e
Create Date: 2026-09-15 17:35:51.417285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caa6e1b8a5f6'
down_revision: Union[str, Sequence[str], None] = 'b8f816a7712e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
